services:
  - type: web
    name: documenteditor-server
    env: node
    rootDir: server
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 4000
